term xterm-256color

remember_window_size no
initial_window_width 100c
initial_window_height 30c

background_opacity 0.8

font_family monospace
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0

scrollback_lines 10000
wheel_scroll_multiplier 3.0

copy_on_select clipboard
mouse_hide_wait -1
mouse_map middle release ungrabbed paste_from_selection

cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval 0.5
cursor_underline_thickness 1.0

foreground #D8DEE9
background #2E3440

color0  #3B4252
color1  #BF616A
color2  #A3BE8C
color3  #EBCB8B
color4  #81A1C1
color5  #B48EAD
color6  #88C0D0
color7  #E5E9F0

color8  #4C566A
color9  #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #8FBCBB
color15 #ECEFF4

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map shift+page_up scroll_page_up
map shift+page_down scroll_page_down
map shift+home scroll_home
map shift+end scroll_end
map ctrl+0 change_font_size all 0

open_url_with zen-browser
