[Autologin]

[General]
InputMethod=qtvirtualkeyboard
GreeterEnvironment=QML2_IMPORT_PATH=/usr/share/sddm/themes/silent/components/,QT_IM_MODULE=qtvirtualkeyboard
GreeterEnvironment=QT_SCALE_FACTOR=1.5,QT_FONT_DPI=144

[Wayland]
EnableHiDPI=true

[X11]
EnableHiDPI=true
ServerArguments=-dpi 144

[Theme]
Current=silent
